#Ryan Peterson Student ID: 000980429
#Using Vagrant for local test deployment with Chef Kitchen
driver:
  name: vagrant
  network:
    - ["public_network"] 
  customize:
    cpus: 1
    memory: 512
provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.9
verifier:
  name: inspec
platforms:
  - name: centos-7

suites:
# Satellite Terminal Server
  - name: satellite_terminal_server
    driver:
      vm_hostname: terminal.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Master Time Server
  - name: master_time_server
    driver:
      vm_hostname: time.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Web Server
  - name: web_server
    driver:
      vm_hostname: web.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Database Server
  - name: database_server
    driver:
      vm_hostname: database.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Scaled Satellite Terminal Server
  - name: scaled_satellite_terminal_server
    driver:
      vm_hostname: scaled-terminal.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Scaled Web Server
  - name: scaled_web_server
    driver:
      vm_hostname: scaled-web.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:

# Scaled Time Server
  - name: scaled_time_server
    driver:
      vm_hostname: scaled-time.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes:
 
# Scaled Database Server
  - name: scaled_database_server
    driver:
      vm_hostname: scaled-database.satelliteads.local
    run_list:
      - recipe[WGU-D085-Chef::default]
    attributes: